
SET(CMAKE_SYSTEM_NAME Linux)

SET(TOOLCHAIN_DIR $ENV{HOME}/toolchain_3528)
set(CMAKE_CROSSCOMPILING true)

SET(CMAKE_CXX_COMPILER ${TOOLCHAIN_DIR}/host/usr/bin/mips-linux-gnu-g++)
SET(CMAKE_C_COMPILER ${TOOLCHAIN_DIR}/host/usr/bin/mips-linux-gnu-gcc)
SET(CMAKE_FIND_ROOT_PATH ${TOOLCHAIN_DIR}/target/mipsel-buildroot-linux-gnu)
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(DIRECTFB_INCLUDE_DIR  ${TOOLCHAIN_DIR}/target/mipsel-buildroot-linux-gnu/sysroot/usr/include/directfb)
